apiVersion: v1
kind: LimitRange
metadata:
  name: chapter-6-limitrange
spec:
  limits:
    - type: Container
      max:
        cpu: "2"
        memory: 1Gi
      min:
        cpu: 100m
        memory: 100Mi
      default:
        cpu: 500m
        memory: 300Mi
      defaultRequest:
        cpu: 200m
        memory: 100Mi
      maxLimitRequestRatio:
        cpu: "10"
