apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 3scale-operator
  namespace: openshift-3scale-operator
spec:
  channel: threescale-2.15
  startingCSV: 3scale-operator.v0.12.0
  namespace: openshift-3scale-operator
  sourceNamespace: openshift-marketplace
  name: 3scale-operator
  source: redhat-operators
  installPlanApproval: Manual
  config:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node-role.kubernetes.io/infra
              operator: Exists
    tolerations:
    - key: node-role.kubernetes.io/infra
      effect: NoExecute
