apiVersion: security.openshift.io/v1 
kind: SecurityContextConstraints 
metadata: 
  name: my-scc 
allowPrivilegedContainer: false 
readOnlyRootFilesystem: false 
requiredDropCapabilities: 
  - KILL 
  - MKNOD 
runAsUser: 
  type: RunAsAny 
fsGroup: 
  type: MustRunAs 
  ranges: 
    - min: 1000 
      max: 2000 
volumes: 
  - configMap 
  - downwardAPI 
  - emptyDir 
  - persistentVolumeClaim 
  - secret 
