apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  labels:
    dashboards: grafana-demo
    folders: grafana-demo
  name: grafana-demo
  namespace: openshift-operators
spec:
  route: grafana-demo.apps.CLUSTER_NAME.DOMAIN
  config:
    auth:
      disable_login_form: "false"
    log:
      mode: console
    security:
      admin_password: start
      admin_user: root
