apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  annotations:
    maistra.io/mesh-generation: 2.6.5-1-2
  finalizers:
  - kiali.io/finalizer
  labels:
    app.kubernetes.io/component: kiali
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 2.6.5-1-2
    maistra-version: 2.5.8
    maistra.io/owner: istio-system
    maistra.io/owner-name: basic
  name: kiali
  namespace: istio-system
spec:
  api:
    namespaces:
      exclude: []
  auth:
    strategy: openshift
  deployment:
    accessible_namespaces:
    - bookinfo
    - tracing-system
    image_pull_policy: ""
    ingress:
      enabled: true
    namespace: istio-system
    pod_labels:
      sidecar.istio.io/inject: "false"
  external_services:
    custom_dashboards:
      namespace_label: kubernetes_namespace
    grafana:
      auth:
        password: CrP873ElpZQArLemYCXUXXx4OUHzX2nw5ppBEN3vpEqwIXBVX+Rd8Ee1Mzw9C/wQ0EagnF5FjgQI+KZUMacrzgM3v0ews9WtQUj/ytjLbbYl+0z0a3+AwHrRkiGj2KdwzPqoY94hr1jkBcCv7DW9IWySmbAID/f7RrTnTpBhIm538fjMWd7nm7j8JAYXnKpCQrFeGI2wKwDi9t4HkhqbCyoluTqL7nRyXO8oRohF8xrqcG2n1VQecGl8ty8LDMvRKgYCxmYfFBqAaKiyvgZvj7KJ8YDYjFrVpmSOfrxShWkZvLjjcC2Zsn4XH4a0V9n9yzGrW4lA4rVdATy3E31y
        type: basic
        use_kiali_token: false
        username: internal
      enabled: true
      in_cluster_url: https://grafana.istio-system.svc:3000
      url: https://grafana-istio-system.apps.cluster.example.com
    istio:
      config_map_name: istio-basic
      istio_sidecar_injector_config_map_name: istio-sidecar-injector-basic
      istiod_deployment_name: istiod-basic
      url_service_version: http://istiod-basic.istio-system:15014/version
    prometheus:
      auth:
        password: CrP873ElpZQArLemYCXUXXx4OUHzX2nw5ppBEN3vpEqwIXBVX+Rd8Ee1Mzw9C/wQ0EagnF5FjgQI+KZUMacrzgM3v0ews9WtQUj/ytjLbbYl+0z0a3+AwHrRkiGj2KdwzPqoY94hr1jkBcCv7DW9IWySmbAID/f7RrTnTpBhIm538fjMWd7nm7j8JAYXnKpCQrFeGI2wKwDi9t4HkhqbCyoluTqL7nRyXO8oRohF8xrqcG2n1VQecGl8ty8LDMvRKgYCxmYfFBqAaKiyvgZvj7KJ8YDYjFrVpmSOfrxShWkZvLjjcC2Zsn4XH4a0V9n9yzGrW4lA4rVdATy3E31y
        type: basic
        use_kiali_token: false
        username: internal
      url: https://prometheus.istio-system.svc:9090
    tracing:
      auth:
        password: CrP873ElpZQArLemYCXUXXx4OUHzX2nw5ppBEN3vpEqwIXBVX+Rd8Ee1Mzw9C/wQ0EagnF5FjgQI+KZUMacrzgM3v0ews9WtQUj/ytjLbbYl+0z0a3+AwHrRkiGj2KdwzPqoY94hr1jkBcCv7DW9IWySmbAID/f7RrTnTpBhIm538fjMWd7nm7j8JAYXnKpCQrFeGI2wKwDi9t4HkhqbCyoluTqL7nRyXO8oRohF8xrqcG2n1VQecGl8ty8LDMvRKgYCxmYfFBqAaKiyvgZvj7KJ8YDYjFrVpmSOfrxShWkZvLjjcC2Zsn4XH4a0V9n9yzGrW4lA4rVdATy3E31y
        type: basic
        use_kiali_token: false
        username: internal
      enabled: false
      in_cluster_url: "http://tempo-sample-query-frontend.tracing-system.svc.cluster.local:16685"
      namespace: istio-system
      service: ""
      url: "tempo-simplest-query-frontend-tracing-system.apps.cluster.example.com"
      use_grpc: true
  installation_tag: Kiali [istio-system]
  istio_namespace: istio-system
  version: v1.73
