apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  template:
    metadata:
      annotations: {}
    spec:
      serviceAccountName: webserver
      containers:
      - name: webserver 
        image: nginx
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: index
        configMap:
          name: webserver-index-page
