apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webserver-to-anyuid-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-anyuid-scc
subjects:
- kind: ServiceAccount
  name: webserver
  namespace: chapter-9-kustomize
