apiVersion: autoscaling.k8s.io/v1 
kind: VerticalPodAutoscaler 
metadata: 
  name: example-vpa 
  namespace: your-namespace 
spec: 
  targetRef: 
    apiVersion: "apps/v1" 
    kind:       Deployment 
    name:       example-deployment 
  updatePolicy: 
    updateMode: "Off" 
