apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: openshift-storage
data:
  CSI_PLUGIN_TOLERATIONS: |
    - key: node-role.kubernetes.io/infra
      effect: NoExecute
