apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |+
    prometheus:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-storagecluster-cephfs
          resources:
            requests:
              storage: 40Gi
    thanosRuler:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-storagecluster-cephfs
          resources:
            requests:
              storage: 20Gi
