apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  labelSelector:
    matchLabels:
      node-role.kubernetes.io/infra: ""
  placement:
    all:
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
    arbiter:
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
    osd:
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
    osd-prepare:
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
    rbd-mirror:
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
    mon:
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
    mds:
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
    rgw:
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
    noobaa-core:
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
    noobaa-standalone:
      tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoExecute
  network:
    connections:
      encryption:
        enabled: true
  resourceProfile: lean
  storageDeviceSets:
  - config: {}
    count: 1
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 512Gi
        storageClassName: thin-csi
        volumeMode: Block
    name: ocs-deviceset-thin-csi
    portable: true
    replica: 3
