apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry
  namespace: openshift-image-registry
spec:
  resources:
    requests:
      storage: 30Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
