apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: windows-2022
handler: runhcs-wcow-process
scheduling:
  nodeSelector: 
    kubernetes.io/os: windows
    kubernetes.io/arch: amd64
    node.kubernetes.io/windows-build: '10.0.20348'
  tolerations: 
  - effect: NoSchedule
    key: os
    operator: Equal
    value: windows
  - effect: NoSchedule
    key: os
    operator: Equal
    value: Windows
