apiVersion: v1
kind: Service
metadata:
  name: win-webserver
  namespace: windows-demo
  labels:
    app: win-webserver
spec:
  selector:
    app: win-webserver
  ports:
  - port: 80
    targetPort: 80
