apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: <CLUSTER_INFRA_ID>
  name: <CLUSTER_INFRA_ID>-infra
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <CLUSTER_INFRA_ID>
      machine.openshift.io/cluster-api-machineset: <CLUSTER_INFRA_ID>-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: <CLUSTER_INFRA_ID> 
        machine.openshift.io/cluster-api-machine-role: infra 
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: <CLUSTER_INFRA_ID>-infra
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      taints: 
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 100
          kind: VSphereMachineProviderSpec
          memoryMiB: 32768
          network:
            devices:
            - networkName: "<NETWORK_NAME>" 
          numCPUs: 8
          numCoresPerSocket: 1
          snapshot: ""
          template: <RHCOS_OVA_NAME>
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: <DATACENTER>
            datastore: /<DATACENTER>/datastore/<DATASTORE>
            folder: /<DATACENTER>/vm/<VM_FOLDER>
            resourcepool: /<DATACENTER>/host/<CLUSTER>/<RESOURCE_POOL>
            server: <VSPHERE_HOSTNAME_OR_IP>
