apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "learning-ocp4-nginx.fullname" . }}
  labels:
    {{- include "learning-ocp4-nginx.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*.html").AsConfig | indent 2 }}
