apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "learning-ocp4-nginx.fullname" . }}
  labels:
    {{- include "learning-ocp4-nginx.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "learning-ocp4-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "learning-ocp4-nginx.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "learning-ocp4-nginx.serviceAccountName" . }}
      containers:
      - name: nginx 
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: index
        configMap:
          name: {{ include "learning-ocp4-nginx.fullname" . }}
