apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "learning-ocp4-nginx.roleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-anyuid-scc
subjects:
- kind: ServiceAccount
{{- if .Values.serviceAccount.create }}
  name: {{ include "learning-ocp4-nginx.serviceAccountName" . }}
{{- else }}
  name: default
{{- end }}
  namespace: {{ .Release.Namespace }}
