apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "learning-ocp4-nginx.fullname" . }}
  labels:
    {{- include "learning-ocp4-nginx.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "learning-ocp4-nginx.fullname" . }}
