apiVersion: v1
kind: Service
metadata:
  name: {{ include "learning-ocp4-nginx.fullname" . }}
  labels:
    {{- include "learning-ocp4-nginx.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "learning-ocp4-nginx.selectorLabels" . | nindent 4 }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
