replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "alpine"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  openshift.io/required-scc: anyuid
podLabels: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

route:
  host: nginx-demo.apps.CLUSTER_NAME.DOMAIN

roleBinding:
  name: ""
