apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: my-awesome-project-01
spec:
  containers:
    - name: example-container
      image: registry.access.redhat.com/ubi9/ubi:latest
      command: ["sleep", "3600"]
      env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: example-configmap
              key: log.level
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: example-configmap

