apiVersion: v1
kind: Pod
metadata:
  name: example-pod-secret
  namespace: my-awesome-project-01
spec:
  containers:
    - name: example-container
      image: registry.access.redhat.com/ubi9/ubi:latest
      command: ["sleep", "3600"]

      # Consume secret as environment variables
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: password

      # Consume secret as mounted files
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret"
          readOnly: true

  volumes:
    - name: secret-volume
      secret:
        secretName: example-secret
